version: '3.8'
services:
  web:
    container_name: "${COMPOSE_PROJECT_NAME}"
    image: "${COMPOSE_PROJECT_NAME}:${VERSION}"
    build:
      # the path of the Dockerfile, or a url to git repository
      context: ./
      # target: this is the stage defined in the Dockerfile
      target: runner
      args:
        - NODE_ENV=${NODE_ENV}
        - BUILD_ENV=${BUILD_ENV}
        - DEBUGGER_PORT=${DEBUGGER_PORT}
        - HOST_PORT=${HOST_PORT}
    # use CMD command ( from Dockerfile )
    # command: ${COMMAND}
    ports:
      # HOST_PORT:CONTAINER_PORT -> the port of the host : the exposed port of the docker container
      - "${HOST_PORT}:${HOST_PORT}"
      - "${DEBUGGER_PORT}:${DEBUGGER_PORT}"
